# Generated by Django 5.2.1 on 2025-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Как готовить'),
        ),
    ]
